import 'dart:convert';

Mi_Perfil_M objetFromJson(String str) => Mi_Perfil_M.fromJson(json.decode(str));
String objetToJson(Mi_Perfil_M data) => json.encode(data.toJson());

class Mi_Perfil_M {
  Mi_Perfil_M(
      {this.id_firestore,
      this.direccion,
      this.nacimiento,
      this.nombres,
      this.apellidop,
      this.apellidom,
      this.foto,
      this.fecha_registro,
      this.fecha_memebresia,
      this.correo,
      this.telefono,
      this.fecha_ultima_transaccion,
      this.id_conductor,
      this.cs,
      this.curp,
      this.rfc,
      this.pago_viaje,
      this.pago_membresia,
      this.pago_adeudo,
      this.saldo_membresia,
      this.rating,
      this.estado,
      this.viajes_exitosos,
      this.viajes_cancelados,
      this.raites,
      this.id,
      this.id_viaje,
      this.calif,
      this.viajes}); //

  String id_firestore,
      direccion,
      nacimiento,
      nombres,
      apellidop,
      apellidom,
      foto,
      fecha_registro,
      fecha_memebresia,
      correo,
      telefono,
      fecha_ultima_transaccion,
      id_conductor,
      cs,
      curp,
      rfc,
      id_viaje;
  double pago_viaje, pago_membresia, pago_adeudo, saldo_membresia, rating;
  int estado, viajes_exitosos, viajes_cancelados, raites, id, calif, viajes;

  factory Mi_Perfil_M.fromJson(Map<String, dynamic> json) => Mi_Perfil_M(
      id_firestore: json["id_firestore"],
      direccion: json["direccion"],
      nacimiento: json["nacimiento"],
      nombres: json["nombres"],
      apellidop: json["apellidop"],
      apellidom: json["apellidom"],
      foto: json["foto"],
      fecha_registro: json["fecha_registro"],
      fecha_memebresia: json["fecha_memebresia"],
      correo: json["correo"],
      telefono: json["telefono"],
      fecha_ultima_transaccion: json["fecha_ultima_transaccion"],
      id_conductor: json["id_conductor"],
      cs: json["cs"],
      curp: json["curp"],
      rfc: json["rfc"],
      pago_viaje: json["pago_viaje"],
      pago_membresia: json["pago_membresia"],
      pago_adeudo: json["pago_adeudo"],
      saldo_membresia: json["saldo_membresia"],
      rating: json["rating"],
      estado: json["estado"],
      viajes_exitosos: json["viajes_exitosos"],
      viajes_cancelados: json["viajes_cancelados"],
      raites: json["raites"],
      id: json["id"],
      id_viaje: json["id_viaje"],
      calif: json["calif"],
      viajes: json["viajes"]);

  Map<String, dynamic> toJson() => {
        "id_firestore": id_firestore,
        "direccion": direccion,
        "nacimiento": nacimiento,
        "nombres": nombres,
        "apellidop": apellidop,
        "apellidom": apellidom,
        "foto": foto,
        "fecha_registro": fecha_registro,
        "fecha_memebresia": fecha_memebresia,
        "correo": correo,
        "telefono": telefono,
        "fecha_ultima_transaccion": fecha_ultima_transaccion,
        "id_conductor": id_conductor,
        "cs": cs,
        "curp": curp,
        "rfc": rfc,
        "pago_viaje": pago_viaje,
        "pago_membresia": pago_membresia,
        "pago_adeudo": pago_adeudo,
        "saldo_membresia": saldo_membresia,
        "rating": rating,
        "estado": estado,
        "viajes_exitosos": viajes_exitosos,
        "viajes_cancelados": viajes_cancelados,
        "raites": raites,
        "id": id,
        "id_viaje": id_viaje,
        "calif": calif,
        "viajes": viajes
      };
}
