import 'dart:convert';

Perfil_conductor_M objetFromJson(String str) =>
    Perfil_conductor_M.fromJson(json.decode(str));
String objetToJson(Perfil_conductor_M data) => json.encode(data.toJson());

class Perfil_conductor_M {
  Perfil_conductor_M(
      {this.id,
      this.correo,
      this.uid,
      this.RFC,
      this.cs,
      this.CURP,
      this.foto,
      this.nombres,
      this.aP,
      this.aM,
      this.direccion,
      this.NLicencia,
      this.NTarje,
      this.tipo_perfil,
      this.cA,
      this.viajes,
      this.registro,
      this.sesion,
      this.telefono,
      this.r1,
      this.r2,
      this.r3,
      this.r4,
      this.r5,
      this.r6,
      this.r7,
      this.r8,
      this.r9,
      this.r10});

  String correo,
      uid,
      RFC,
      cs,
      CURP,
      foto,
      nombres,
      aP,
      aM,
      direccion,
      NLicencia,
      NTarje,
      tipo_perfil,
      registro,
      sesion;

  int id, cA, viajes, telefono, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10;

  factory Perfil_conductor_M.fromJson(Map<String, dynamic> json) =>
      Perfil_conductor_M(
          id: json["id"],
          correo: json["correo"],
          uid: json["uid"],
          RFC: json["RFC"],
          cs: json["cs"],
          CURP: json["CURP"],
          foto: json["foto"],
          nombres: json["nombres"],
          aP: json["aP"],
          aM: json["aM"],
          direccion: json["direccion"],
          NLicencia: json["NLicencia"],
          NTarje: json["NTarje"],
          tipo_perfil: json["tipo_perfil"],
          cA: json["cA"],
          viajes: json["viajes"],
          registro: json["registro"],
          sesion: json["sesion"],
          telefono: json["telefono"],
          r1: json["r1"],
          r2: json["r2"],
          r3: json["r3"],
          r4: json["r4"],
          r5: json["r5"],
          r6: json["r6"],
          r7: json["r7"],
          r8: json["r8"],
          r9: json["r9"],
          r10: json["r10"]);
  Map<String, dynamic> toJson() => {
        "id": id,
        "correo": correo,
        "uid": uid,
        "RFC": RFC,
        "cs": cs,
        "CURP": CURP,
        "foto": foto,
        "nombres": nombres,
        "aP": aP,
        "aM": aM,
        "direccion": direccion,
        "NLicencia": NLicencia,
        "NTarje": NTarje,
        "tipo_perfil": tipo_perfil,
        "cA": cA,
        "viajes": viajes,
        "registro": registro,
        "sesion": sesion,
        "telefono": telefono,
        "r1": r1,
        "r2": r2,
        "r3": r3,
        "r4": r4,
        "r5": r5,
        "r6": r6,
        "r7": r7,
        "r8": r8,
        "r9": r9,
        "r10": r10
      };
}
