class Reg_viaje {
  Reg_viaje(
      {this.id,
      this.viajes_chofer,
      this.puntos_chofer,
      this.puntos_v1,
      this.puntos_v2,
      this.puntos_v3,
      this.viajes_v1,
      this.viajes_v2,
      this.viajes_v3,
      this.estado_viaje1,
      this.estado_viaje2,
      this.estado_viaje3,
      this.pasajeros1,
      this.pasajeros2,
      this.pasajeros3,
      this.lat_chofer,
      this.lon_chofer,
      this.lat_origen1,
      this.lon_origen1,
      this.lat_destino1,
      this.lon_destino1,
      this.lat_origen2,
      this.lon_origen2,
      this.lat_destino2,
      this.lon_destino2,
      this.lat_origen3,
      this.lon_origen3,
      this.lat_destino3,
      this.lon_destino3,
      this.costo_v1,
      this.costo_v2,
      this.costo_v3,
      this.uid_chofer,
      this.uid_v1,
      this.uid_v2,
      this.uid_v3,
      this.vehiculo,
      this.placas,
      this.foto_chofer,
      this.foto_v1,
      this.foto_v2,
      this.foto_v3,
      this.dir_origen1,
      this.dir_destino1,
      this.dir_origen2,
      this.dir_destino2,
      this.dir_origen3,
      this.dir_destino3,
      this.nombre_chofer,
      this.nombre_v1,
      this.nombre_v2,
      this.nombre_v3,
      this.fecha1,
      this.fecha2,
      this.fecha3,
      this.raites1,
      this.raites2,
      this.raites3});

  ///1=concluido, 2=cancelado por usuario y sin cargo, 3 cancelado por usuario y con cargo
  //4=cancelado por conductor, 5= solicitado, 6=viajando

  String uid_chofer,
      uid_v1,
      uid_v2,
      uid_v3,
      vehiculo,
      placas,
      foto_chofer,
      foto_v1,
      foto_v2,
      foto_v3,
      dir_origen1,
      dir_destino1,
      dir_origen2,
      dir_destino2,
      dir_origen3,
      dir_destino3,
      nombre_chofer,
      nombre_v1,
      nombre_v2,
      nombre_v3,
      fecha1,
      fecha2,
      fecha3;
  double lat_chofer,
      lon_chofer,
      lat_origen1,
      lon_origen1,
      lat_destino1,
      lon_destino1,
      lat_origen2,
      lon_origen2,
      lat_destino2,
      lon_destino2,
      lat_origen3,
      lon_origen3,
      lat_destino3,
      lon_destino3,
      costo_v1,
      costo_v2,
      costo_v3;
  int id,
      viajes_chofer,
      puntos_chofer,
      puntos_v1,
      puntos_v2,
      puntos_v3,
      viajes_v1,
      viajes_v2,
      viajes_v3,
      estado_viaje1,
      estado_viaje2,
      estado_viaje3,
      pasajeros1,
      pasajeros2,
      pasajeros3,
      raites1,
      raites2,
      raites3;

  factory Reg_viaje.fromJson(Map<String, dynamic> json) => Reg_viaje(
      id: json["id"],
      raites1: json["raites1"],
      raites2: json["raites2"],
      raites3: json["raites3"],
      viajes_chofer: json["viajes_chofer"],
      puntos_chofer: json["puntos_chofer"],
      puntos_v1: json["puntos_v1"],
      puntos_v2: json["puntos_v2"],
      puntos_v3: json["puntos_v3"],
      viajes_v1: json["viajes_v1"],
      viajes_v2: json["viajes_v2"],
      viajes_v3: json["viajes_v3"],
      estado_viaje1: json["estado_viaje1"],
      estado_viaje2: json["estado_viaje2"],
      estado_viaje3: json["estado_viaje3"],
      pasajeros1: json["pasajeros1"],
      pasajeros2: json["pasajeros2"],
      pasajeros3: json["pasajeros3"],
      lat_chofer: json["lat_chofer"],
      lon_chofer: json["lon_chofer"],
      lat_origen1: json["lat_origen1"],
      lon_origen1: json["lon_origen1"],
      lat_destino1: json["lat_destino1"],
      lon_destino1: json["lon_destino1"],
      lat_origen2: json["lat_origen2"],
      lon_origen2: json["lon_origen2"],
      lat_destino2: json["lat_destino2"],
      lon_destino2: json["lon_destino2"],
      lat_origen3: json["lat_origen3"],
      lon_origen3: json["lon_origen3"],
      lat_destino3: json["lat_destino3"],
      lon_destino3: json["lon_destino3"],
      costo_v1: json["costo_v1"],
      costo_v2: json["costo_v2"],
      costo_v3: json["costo_v3"],
      uid_chofer: json["uid_chofer"],
      uid_v1: json["uid_v1"],
      uid_v2: json["uid_v2"],
      uid_v3: json["uid_v3"],
      vehiculo: json["vehiculo"],
      placas: json["placas"],
      foto_chofer: json["foto_chofer"],
      foto_v1: json["foto_v1"],
      foto_v2: json["foto_v2"],
      foto_v3: json["foto_v3"],
      dir_origen1: json["dir_origen1"],
      dir_destino1: json["dir_destino1"],
      dir_origen2: json["dir_origen2"],
      dir_destino2: json["dir_destino2"],
      dir_origen3: json["dir_origen3"],
      dir_destino3: json["dir_destino3"],
      nombre_chofer: json["nombre_chofer"],
      nombre_v1: json["nombre_v1"],
      nombre_v2: json["nombre_v2"],
      nombre_v3: json["nombre_v3"],
      fecha1: json["fecha1"],
      fecha2: json["fecha2"],
      fecha3: json["fecha3"]);

  Map<String, dynamic> toJson() => {
        "id": id,
        "raites1": raites1,
        "raites2": raites2,
        "raites3": raites3,
        "viajes_chofer": viajes_chofer,
        "puntos_chofer": puntos_chofer,
        "puntos_v1": puntos_v1,
        "puntos_v2": puntos_v2,
        "puntos_v3": puntos_v3,
        "viajes_v1": viajes_v1,
        "viajes_v2": viajes_v2,
        "viajes_v3": viajes_v3,
        "estado_viaje1": estado_viaje1,
        "estado_viaje2": estado_viaje2,
        "estado_viaje3": estado_viaje3,
        "pasajeros1": pasajeros1,
        "pasajeros2": pasajeros2,
        "pasajeros3": pasajeros3,
        "lat_chofer": lat_chofer,
        "lon_chofer": lon_chofer,
        "lat_origen1": lat_origen1,
        "lon_origen1": lon_origen1,
        "lat_destino1": lat_destino1,
        "lon_destino1": lon_destino1,
        "lat_origen2": lat_origen2,
        "lon_origen2": lon_origen2,
        "lat_destino2": lat_destino2,
        "lon_destino2": lon_destino2,
        "lat_origen3": lat_origen3,
        "lon_origen3": lon_origen3,
        "lat_destino3": lat_destino3,
        "lon_destino3": lon_destino3,
        "costo_v1": costo_v1,
        "costo_v2": costo_v2,
        "costo_v3": costo_v3,
        "uid_chofer": uid_chofer,
        "uid_v1": uid_v1,
        "uid_v2": uid_v2,
        "uid_v3": uid_v3,
        "vehiculo": vehiculo,
        "placas": placas,
        "foto_chofer": foto_chofer,
        "foto_v1": foto_v1,
        "foto_v2": foto_v2,
        "foto_v3": foto_v3,
        "dir_origen1": dir_origen1,
        "dir_destino1": dir_destino1,
        "dir_origen2": dir_origen2,
        "dir_destino2": dir_destino2,
        "dir_origen3": dir_origen3,
        "dir_destino3": dir_destino3,
        "nombre_chofer": nombre_chofer,
        "nombre_v1": nombre_v1,
        "nombre_v2": nombre_v2,
        "nombre_v3": nombre_v3,
        "fecha1": fecha1,
        "fecha2": fecha2,
        "fecha3": fecha3
      };
}
